Make sure exclude is not null
java.lang.IllegalArgumentException: Parameter specified as non-null is null: method org.jitsi.jicofo.jigasi.JigasiDetector.selectSipJigasi, parameter exclude